-- À exécuter dans Supabase > SQL Editor
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nom text not null check (char_length(trim(nom)) > 0),
  prenom text not null check (char_length(trim(prenom)) > 0),
  adresse text not null check (char_length(trim(adresse)) > 0),
  tel text not null check (char_length(trim(tel)) > 0),
  participation text not null check (participation in ('oui', 'non'))
);

alter table public.registrations enable row level security;

-- Le formulaire peut créer une inscription sans exposer la lecture des données.
drop policy if exists "Allow public registration inserts" on public.registrations;
create policy "Allow public registration inserts"
on public.registrations
for insert
to anon
with check (true);

-- Aucun select public : les inscriptions se consultent depuis le tableau de bord Supabase.
revoke select on public.registrations from anon, authenticated;
grant insert on public.registrations to anon;
